### ISSUE TITLE
Problème avec la méthode `registerCustomData` et proposition de feature

### ISSUE THREAD

**Issue by AnthoineSG-MTX** [iadvize/iadvize-react-native-sdk#10]
Bonjour,

Nous souhaitons vous proposer quelques sujets de possibles améliorations.

Merci d'avance

- Possibilité de positionner la bulle à droite ou à gauche
  - Pour éviter de devoir faire des calculs de largeur d'écran
- Possibilité de forcer la langue utiliser dans la chat pour les dates notamment
  - Sur iOS les dates ne sont pas au format français alors que les paramètre du téléphone le sont
- Possibilité de modifier la couleur de fond même en light ou dark mode
  - Notre application ne possède pas de dark mode et nous souhaitons garder une cohérence en full light
- La méthode registerCustomData ne semble pas fonctionner :
  - Tests réalisés avec l'[app d'exemple](https://github.com/iadvize/iadvize-react-native-sdk/blob/main/example/lib/App.tsx)
    - Press `activate`
    - Press `activateTargetingRules`
    - Click sur la bulle
    - Envoie d'un message
      - (Sur la console) réception du message (Image 1)
        - Card visiteur avec 3 onglets (Navigation/Information client/Profil)
    - Press `registerCustomData`
      - (Sur la console) après refresh de la page (Image 2)
        - Card visiteur avec 4 onglets (Navigation/Données personnalisées/Information client/Profil)
        - Onglet Données personnalisées sans les données

#### Image 1
<img src="https://github.com/user-attachments/assets/6aa7f436-7fa2-41d0-9972-b8918c221731" width="300" />

#### Image 2
<img src="https://github.com/user-attachments/assets/2126efb5-5aa9-48aa-ab86-3ff02ab9abd7" width="300" />

**Comment by Judas** [comment]
Bonjour,

`Possibilité de positionner la bulle à droite ou à gauche`
on l'a ajouté dans nos product feedbacks

`Possibilité de forcer la langue utiliser dans la chat pour les dates notamment`
pour les textes statiques (dates, messages de contrôles etc...) on utilise en effet la langue du device, après test il y a bien un souci sur iOS x ReactNative qui garde la langue anglaise même avec le device en français (ca fonctionne sur iOS natif mais le  ReactNative semble modifier quelque chose qui casse le fonctionnement)
On va chercher la raison et corriger le souci

`Possibilité de modifier la couleur de fond même en light ou dark mode`
le SDK suit la bonne pratique de s'adapter au choix de l'utilisateur en calquant la UI sur le mode light ou dark. Si votre app est "full light" je vous propose d'utiliser la commande qui permet de forcer le mode light/dark ce qui aura pour effet de figer la UI du SDK dans l'un ou l'autre des modes. La procédure est décrite ici : https://docs.iadvize.dev/technologies/web-and-mobile-sdk/mobile-sdk/frequently-asked-questions#forcing-light-dark-ui

`La méthode registerCustomData ne semble pas fonctionner`
J'ai pu tester votre scénario et je comprends ce qui cloche. Pour que la custom-data soit visible dans le panneau du pupitre il faut que celle ci soit déclarée dans l'admin (`Engagement -> Settings -> Custom Data`).
Il faut aussi bien vérifier :
- que l'id de la custom data envoyée à l'API corresponde à ce qui est déclaré dans le champ `Variable description`
- que la case `Display the custom data on the chat panel` soit bien cochée

**Comment by simonliotier** [comment]
Bonjour @AnthoineSG-MTX,

En l'absence de @Judas aujourd'hui, je me permets d'apporter quelques précisions concernant le soucis de traductions.  

Votre app gère-t-elle plusieurs langues ? 
Ou au contraire seulement le français, en dur ? Si tel est le cas, cela peut expliquer pourquoi les textes du SDK ne s'affichent pas en français sur iOS.

En effet, le SDK est localisé en 8 langues différentes (dont le français), mais pour qu'iOS déclenche le processus de localisation, il faut que l'app qui embarque elle-même le SDK soit localisée (sinon ça fallback sur l'anglais). Pour ça, 2 étapes sont nécessaires dans Xcode : 

1. Au niveau du projet, ajouter le Français dans la liste des localisations supportées.
<img width="1624" alt="Step1" src="https://github.com/user-attachments/assets/20e0764d-0b3b-4a74-bc9d-e75c1211b49b">

2. Ajouter au moins un fichier de localizations (il peut être vide) et s'assurer que la localisation française est activée pour ce fichier.
	- File > New > File... > Strings File (Legacy)
	- Cocher le français dans l'inspecteur à droite
<img width="1624" alt="Step2a" src="https://github.com/user-attachments/assets/e3bc7377-d500-4731-aa86-9bff4ed4c7d2">
<img width="1624" alt="Step2b" src="https://github.com/user-attachments/assets/411d5ac6-3195-4666-adc5-87c9634adfc9">

Avec ça en place, iOS prendra en charge la localisation et le SDK s'adaptera à la langue du téléphone.

A noter que cela ne devrait rien changer pour votre app, si comme je l'ai supposé, vos textes français sont en dur.

**Comment by jeromeMTX** [comment]
Bonjour @simonliotier,
je mets cela en place de suite
Merci beaucoup de votre aide
Jerome

**Comment by Judas** [comment]
@jeromeMTX le plus simple sous ReactNative pour forcer un mode est probablement de passer par le fichier `ios/project/Info.plist`, en y ajoutant une entrée : 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        ....
	<key>UIUserInterfaceStyle</key>
	<string>Light</string>
</dict>
</plist>
```

**Comment by jeromeMTX** [comment]
@Judas : merci, j essaye de suite

**Comment by jeromeMTX** [comment]
@Judas : bonjour, la solution proposee  https://docs.iadvize.dev/technologies/web-and-mobile-sdk/mobile-sdk/frequently-asked-questions#forcing-light-dark-ui ne fonctionne pas sur android, elle fait planter les builds. Avez vous autre chose a nous proposer? Merci par avance

**Comment by Judas** [comment]
Bonjour @jeromeMTX, je viens de tester et ca fonctionne correctement avec les changements proposés :

https://github.com/iadvize/iadvize-react-native-sdk/commit/36cc8449959ca04077d9264d68cd1965ee22a541

Quel est le message d'erreur qui s'affiche, lors du build qui plante ?

**Comment by jeromeMTX** [comment]
@Judas : je ne sais plus, je vais relancer un build.
J'ai un autre souci: les infos clients ne remontent pas dans le pupitre du conseiller:`
export const activate: Activate = async ({ user }) => {
  console.log('🚀 ~ constactivate:Activate= ~ user:', user);
  try {
    const userId = (user && user.id) || '';
    await IAdvizeSDK.activate(Number(ENV.IADVIZE_PROJECT_ID), userId, URLS.RGPD);

    const target = (Platform.OS === 'ios' && ENV.IADVIZE_TARGET_IOS) || ENV.IADVIZE_TARGET_ANDROID;
    IAdvizeSDK.activateTargetingRule(target, ConversationChannel.CHAT);

    if (user) {
      const customData = {
        lastName: user.lastName,
        firstName: user.firstName,
        email: user.email,
      };
      IAdvizeSDK.registerCustomData(customData);
    }
  } catch (error) {
    log.error(error);
  }
};`

cela respecte la doc sur le sujet. Y a t'il un parametrage que j'aurais oublié sur la console ou autre?

**Comment by Judas** [comment]
Les custom data ne sont envoyées au pupitre (l'interface de l'agent répondant) que lorsqu'une conversation est en cours.
Si les custom data sont renseignées en dehors d'une conversation en cours, les données sont sauvegardées dans le SDK et envoyées dès qu'une conversation démarre.
Avec le code ci-dessus, les données "lastName", "firstName" et "email" seront envoyées dès qu'une converation poru ce user démarre dans le SDK. 

Attention cependant, [comme dit plus haut](https://github.com/iadvize/iadvize-react-native-sdk/issues/10#issuecomment-2326779114), les custom data doivent être renseignées (avec le même identifiant) dans l'interface d'administration de la solution iAdvize pour que celles-ci soient visible par l'agent dans le pupitre.

<img width="1122" alt="Screenshot 2024-09-16 at 10 01 24" src="https://github.com/user-attachments/assets/a6ce2df9-fd36-40f2-9db6-f580cdd9b159">
<img width="466" alt="Screenshot 2024-09-16 at 10 01 57" src="https://github.com/user-attachments/assets/246054b1-c579-478e-b0c1-6c2e2255e2b1">
<img width="405" alt="Screenshot 2024-09-16 at 10 01 19" src="https://github.com/user-attachments/assets/6b694fb5-c546-4656-82ea-face68a6c317">

**Comment by jeromeMTX** [comment]
Merci @Judas : j'essaye tout cela et vous tiens au courant

**Comment by jeromeMTX** [comment]
Cela fonctionne pour la remontee d'infos dans le pupitre conseiller
pour l'erreur de build android, voici ce que j'ai:
`* What went wrong:
Execution failed for task ':app:checkPreprodReleaseDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class a.a found in modules jetified-iadvize-sdk-2.13.1-rnbackport-runtime (com.iadvize:iadvize-sdk:2.13.1-rnbackport) and jetified-marketingcloudsdk-7.4.4-runtime (com.salesforce.marketingcloud:marketingcloudsdk:7.4.4)
     
     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
`

**Comment by Judas** [comment]
Ce message indique un problème de duplication de dépendance, il doit y avoir une dépendance commune entre le SDK iAdvize et le SDK Salesforce que vous utilisez. Je vais essayer de reproduire la situation pour vous guider dans ce fix.

**Comment by jeromeMTX** [comment]
Nous utilisons actuellement la version :  "react-native-marketingcloudsdk": "^7.5.0"

**Comment by Judas** [comment]
J'ai pu reproduire et corriger le souci. Cela vient d'un conflit d'obfuscation car notre SDK ainsi que celui de Salesforce obfusquent des classes différentes vers le même package.
J'ai donc corrigé cela dans notre SDK, ca sera disponible dans le début de la semaine prochaine. Bon week-end !

**Comment by Judas** [comment]
@jeromeMTX La version `4.2.1` qui corrige le souci d'obfuscation est disponible : https://github.com/iadvize/iadvize-react-native-sdk/releases/tag/4.2.1
