### ISSUE TITLE
Le paramètre `accentColor` ne fonctionne pas sur Android

### ISSUE THREAD

**Issue by mtx-tnguyen** [iadvize/iadvize-react-native-sdk#9]
Dans la [documentation](https://docs.iadvize.dev/technologies/web-and-mobile-sdk/mobile-sdk/cantal#id-3-changing-the-chatbox-colors), il est indiqué que l'on peut changer l'`accentColor` et que cela doit changer la couleur de la bulle `iAdvize`.
Pour info 
- On utilise React Native, on est sur la version 0.73.4 de `react-native`
- On utilise la version 4.0.2 `@iadvize-oss/iadvize-react-native-sdk`
- On a testé la latest (4.1.4) de `@iadvize-oss/iadvize-react-native-sdk` et on a constaté le même problème
- `accentColor` fonctionne bien sur iOS
- Tous les autres paramètres que l'on a testés ont également l'air de marcher correctement (sauf peut-être `incomingMessageAvatarURL`, de nouveau sur Android, mais on n'utilise pas celui-ci)

Est-ce que tu pourrais regarder ce problème @Judas ?
Merci d'avance !

**Comment by Judas** [comment]
`accentColor` ne colore pas les bulles de textes dans la discussion mais les éléments de contrôle additionnel dans les messages. Par exemple : les choix des QCM, le bouton "load past conversations", l'indicateur de frappe, ou encore les messages de type "fichier". Cela colore aussi le bouton d'envoi dans la barre d'input.

Pour changer la couleur des bulles de texte il faut utiliser les variables `incomingMessageBackgroundColor` (pour les messages de l'agent/du bot à gauche) et `outgoingMessageBackgroundColor` (pour les messages du visiteur à droite).

Avec la configuration suivante :
```
incomingMessageBackgroundColor: '#000000',
incomingMessageTextColor: '#FFFFFF',
outgoingMessageBackgroundColor: '#FF0000',
outgoingMessageTextColor: '#00FFFF',
accentColor: '#00FF00',
```

j'obtiens ce rendu (hideux) sur Android et iOS :

![Screenshot_1723539222](https://github.com/user-attachments/assets/2591c0c4-86cd-475e-8351-1a462f88a2f8)

On a bien les messages entrant avec le texte blanc sur noir, les messages sortants en cyan sur rouge, et les éléments additionnels en vert.

@mtx-tnguyen est-il possible d'avoir la `ChatboxConfiguration` qui est envoyée au SDK et le rendu que je puisse comparer / tester et voir le souci ?

**Comment by mtx-tnguyen** [comment]
Hello @Judas, merci pour ta réponse aussi rapide !
De notre côté, on utilise principalement `accentColor` pour changer la couleur de la bulle qui nous permet d'ouvrir le chat.  Ça marche correctement sur iOS, mais pas sur Android. Est-ce qu'il y a une autre propriété dédiée pour ça ?

Sur la capture d'écran, tu trouveras la `ChatboxConfiguration` avec 2 configs suivie du screenshot Android et du screenshot iOS :

![image](https://github.com/user-attachments/assets/413c7244-393b-47a5-b69a-6e86e409aeef)
![image](https://github.com/user-attachments/assets/29569084-410a-49a2-9e07-ff09830cecb3)

Merci d'avance !

**Comment by mtx-tnguyen** [comment]
Merci beaucoup !

**Comment by mtx-tnguyen** [comment]
Waouh, au top ! Merci @Judas, la réactivité mérite une médaille olympique 😛

**Comment by mtx-tnguyen** [comment]
Waouh, au top ! Merci @Judas, la réactivité mérite une médaille olympique 😛
